### ISSUE TITLE
Transfer repo to whatwg?

### ISSUE THREAD

**Issue by domenic** [whatwg/console-spec#15]
I think this is ready to become a WHATWG Standard, if you guys want. Are you interested? If so the first step would be to transfer it to the whatwg organization; then we can get you a subdomain and do a blog post announcement and so on.

**Comment by terinjokes** [comment]
:+1:

**Comment by robertkowalski** [comment]
yay!

**Comment by robertkowalski** [comment]
@terinjokes i think you have to move it, as you are the owner. you could transfer it to domenic as intermediate step...

**Comment by terinjokes** [comment]
Then we would have two levels of redirects :(. I can't move it because I'm not part of WHATWG. Unless someone there wants to make a team for console: https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

**Comment by robertkowalski** [comment]
i tried two level repo moves recently, the last time i tried github was
handing them well (redirected me to the apache org and not to the
intermediate owner)

**Comment by terinjokes** [comment]
@domenic do you have a preference?

**Comment by domenic** [comment]
We can try the temporary admin team for a single-off transfer

**Comment by terinjokes** [comment]
@domenic it's giving an error at the moment, I'm going to transfer to you.

**Comment by domenic** [comment]
I thin kI just need to make the team admins somehow; I don't know how...

**Comment by terinjokes** [comment]
And now we're here. :+1: Thanks @domenic!
